import { FindExactDifficultyConfig, HorizonDifficultyConfig } from '../types/game';

export const FIND_EXACT_DIFFICULTIES: FindExactDifficultyConfig[] = [
  {
    level: 1,
    gridSize: 2,
    verticesMin: 4,
    verticesMax: 5,
    mutationStrength: 0.26,
    timeLimit: 15000,
    trialsCount: 8,
    nearMissCount: 0,
    nearMissStrengthMultiplier: 0.72,
  },
  {
    level: 2,
    gridSize: 2,
    verticesMin: 5,
    verticesMax: 6,
    mutationStrength: 0.22,
    timeLimit: 12000,
    trialsCount: 10,
    nearMissCount: 1,
    nearMissStrengthMultiplier: 0.68,
  },
  {
    level: 3,
    gridSize: 3,
    verticesMin: 5,
    verticesMax: 7,
    mutationStrength: 0.18,
    timeLimit: 12000,
    trialsCount: 10,
    nearMissCount: 1,
    nearMissStrengthMultiplier: 0.62,
  },
  {
    level: 4,
    gridSize: 3,
    verticesMin: 6,
    verticesMax: 8,
    mutationStrength: 0.15,
    timeLimit: 10000,
    trialsCount: 12,
    nearMissCount: 2,
    nearMissStrengthMultiplier: 0.62,
  },
  {
    level: 5,
    gridSize: 4,
    verticesMin: 7,
    verticesMax: 10,
    mutationStrength: 0.12,
    timeLimit: 10000,
    trialsCount: 12,
    nearMissCount: 3,
    nearMissStrengthMultiplier: 0.58,
  },
];

export const HORIZON_DIFFICULTIES: HorizonDifficultyConfig[] = [
  {
    level: 1,
    gridSize: 3,
    verticesMin: 0,
    verticesMax: 0,
    mutationStrength: 0,
    timeLimit: 20000,
    trialsCount: 8,
    minTransformSteps: 1,
    maxMoves: 6,
  },
  {
    level: 2,
    gridSize: 3,
    verticesMin: 0,
    verticesMax: 0,
    mutationStrength: 0,
    timeLimit: 15000,
    trialsCount: 10,
    minTransformSteps: 2,
    maxMoves: 6,
  },
  {
    level: 3,
    gridSize: 4,
    verticesMin: 0,
    verticesMax: 0,
    mutationStrength: 0,
    timeLimit: 15000,
    trialsCount: 10,
    minTransformSteps: 2,
    maxMoves: 5,
  },
  {
    level: 4,
    gridSize: 4,
    verticesMin: 0,
    verticesMax: 0,
    mutationStrength: 0,
    timeLimit: 12000,
    trialsCount: 12,
    minTransformSteps: 3,
    maxMoves: 5,
  },
  {
    level: 5,
    gridSize: 5,
    verticesMin: 0,
    verticesMax: 0,
    mutationStrength: 0,
    timeLimit: 10000,
    trialsCount: 12,
    minTransformSteps: 3,
    maxMoves: 4,
  },
];

export const ADAPTIVE_RULES = {
  promoteStreakThreshold: 3,
  demoteErrorThreshold: 2,
  fatigueThreshold: 0.5,
  targetAccuracy: 0.8,
  rtTargetMultiplier: 0.85,
};

export const MODULE_INFO = {
  'find-exact': {
    id: 'find-exact' as const,
    title: 'Найди точный',
    subtitle: 'Внимание к микродеталям',
    description: 'Найдите точное совпадение среди похожих фигур. Тренирует визуальную точность и распознавание деталей.',
    icon: 'Crosshair' as const,
    color: '#00E5A0',
    colorDim: 'rgba(0, 229, 160, 0.12)',
  },
  'restore-horizon': {
    id: 'restore-horizon' as const,
    title: 'Восстанови горизонт',
    subtitle: 'Пространственная ориентация',
    description: 'Восстановите правильную ориентацию трансформированных паттернов. Развивает пространственное мышление.',
    icon: 'RotateCcw' as const,
    color: '#3B82F6',
    colorDim: 'rgba(59, 130, 246, 0.12)',
  },
};
